[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.17"
solana-sdk = "1.17"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
futures = "0.3"
serde_json = "1.0"
